#ifndef VERSION_H
#define VERSION_H

#include <Arduino.h>

// Auto-generated by pre_build.py

// Git SHA information
const char* const GIT_SHA = "unchecked";
const char* const GIT_SHA_DISPLAY = "built from unchecked-in code";

// Build timestamp
const char* const BUILD_DATE = "Jun 15 2025";
const char* const BUILD_TIME = "15:47:23";

// For backward compatibility
#define BUILD_TIMESTAMP (String(BUILD_DATE) + " " + String(BUILD_TIME))

// Function to get the git SHA as a String
inline String getGitSha() {
    return String(GIT_SHA_DISPLAY);
}

#endif // VERSION_H
